sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: devops-advanced-demo
        api_key: $HEROKU_AUTH_TOKEN
        on: sf-stages-demo
    - stage: test staging
      script: 'curl https://devops-advanced-demo.herokuapp.com'
    - stage: deploy to production
      script: /bin/true
      deploy:
        <<: *heroku
        app: devops-demo-production
    - stage: test production
      script: 'curl http://devops-demo-production.herokuapp.com'
