dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
- 3.0.2

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

jobs:
  include:
    - stage: unit tests
      script: bundle exec rubocop
    - stage: unit tests
      script: bundle exec rake
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: devops-advanced-demo
        api_key: $HEROKU_AUTH_TOKEN
        on: master
    - stage: test staging
      script: 'curl https://devops-advanced-demo.herokuapp.com'
    - stage: deploy to production
      script: /bin/true
      deploy:
        <<: *heroku
        app: devops-demo-production
    - stage: test production
      script: 'curl http://devops-demo-production.herokuapp.com'
